const images = {
    logo: require("~/assests/images//hiequego.png"),
    arsenal: require("~/assests/images/logos/arsenal.png"),
    chelsea: require("~/assests/images/logos/chelsea.png"),
    liverpool: require("~/assests/images/logos/liverpool.png"),
    mancity: require("~/assests/images/logos/manchestercity.png"),
    manutd: require("~/assests/images/logos/manchesterunited.png"),
    tottenham: require("~/assests/images/logos/tottenham.png"),
    atletico: require("~/assests/images/logos/atleticomadrid.png"),
    barcelona: require("~/assests/images/logos/barcelona.png"),
    realmadrid: require("~/assests/images/logos/realmadrid.png"),
    bayern: require("~/assests/images/logos/bayernmunich.png"),
    dortmund: require("~/assests/images/logos/dortmund.png"),
    acmilan: require("~/assests/images/logos/acmilan.png"),
    roma: require("~/assests/images/logos/asroma.png"),
    intermilan: require("~/assests/images/logos/intermilan.png"),
    juventus: require("~/assests/images/logos/juventus.png"),
    psg: require("~/assests/images/logos/psg.png"),
    mls: require("~/assests/images/logos/MLS.png"),
    spl: require("~/assests/images/logos/SPL.png"),

    mancity1: require("~/assests/images/Shirt/mancity/ao1.jpg"),
    mancity2: require("~/assests/images/Shirt/mancity/ao2.jpg"),
    mancity3: require("~/assests/images/Shirt/mancity/ao3.jpg"),
    mancity4: require("~/assests/images/Shirt/mancity/ao4.jpg"),
    mancity5: require("~/assests/images/Shirt/mancity/ao5.jpg"),
    mancity6: require("~/assests/images/Shirt/mancity/ao6.jpg"),
    mancity7: require("~/assests/images/Shirt/mancity/ao7.jpg"),
    mancity8: require("~/assests/images/Shirt/mancity/ao8.jpg"),
    mancity9: require("~/assests/images/Shirt/mancity/ao9.jpg"),
    mancity10: require("~/assests/images/Shirt/mancity/ao10.jpg"),
    mancity11: require("~/assests/images/Shirt/mancity/ao11.jpg"),
    mancity12: require("~/assests/images/Shirt/mancity/ao12.jpg"),

    arsenal1: require("~/assests/images/Shirt/arsenal/ao1.jpg"),
    arsenal2: require("~/assests/images/Shirt/arsenal/ao2.jpg"),
    arsenal3: require("~/assests/images/Shirt/arsenal/ao3.jpg"),
    arsenal4: require("~/assests/images/Shirt/arsenal/ao4.jpg"),
    arsenal5: require("~/assests/images/Shirt/arsenal/ao5.jpg"),
    arsenal6: require("~/assests/images/Shirt/arsenal/ao6.jpg"),
    arsenal7: require("~/assests/images/Shirt/arsenal/ao7.jpg"),
    arsenal8: require("~/assests/images/Shirt/arsenal/ao8.jpg"),
    arsenal9: require("~/assests/images/Shirt/arsenal/ao9.jpg"),
    arsenal10: require("~/assests/images/Shirt/arsenal/ao10.jpg"),
    arsenal11: require("~/assests/images/Shirt/arsenal/ao11.jpg"),
    arsenal12: require("~/assests/images/Shirt/arsenal/ao12.jpg"),

    chelsea1: require("~/assests/images/Shirt/chelsea/ao1.jpg"),
    chelsea2: require("~/assests/images/Shirt/chelsea/ao2.jpg"),
    chelsea3: require("~/assests/images/Shirt/chelsea/ao3.jpg"),
    chelsea4: require("~/assests/images/Shirt/chelsea/ao4.jpg"),
    chelsea5: require("~/assests/images/Shirt/chelsea/ao5.jpg"),
    chelsea6: require("~/assests/images/Shirt/chelsea/ao6.jpg"),
    chelsea7: require("~/assests/images/Shirt/chelsea/ao7.jpg"),
    chelsea8: require("~/assests/images/Shirt/chelsea/ao8.jpg"),
    chelsea9: require("~/assests/images/Shirt/chelsea/ao9.jpg"),
    chelsea10: require("~/assests/images/Shirt/chelsea/ao10.jpg"),
    chelsea11: require("~/assests/images/Shirt/chelsea/ao11.jpg"),
    chelsea12: require("~/assests/images/Shirt/chelsea/ao12.jpg"),

    liverpool1: require("~/assests/images/Shirt/liverpool/ao1.jpg"),
    liverpool2: require("~/assests/images/Shirt/liverpool/ao2.jpg"),
    liverpool3: require("~/assests/images/Shirt/liverpool/ao3.jpg"),
    liverpool4: require("~/assests/images/Shirt/liverpool/ao4.jpg"),
    liverpool5: require("~/assests/images/Shirt/liverpool/ao5.jpg"),
    liverpool6: require("~/assests/images/Shirt/liverpool/ao6.jpg"),
    liverpool7: require("~/assests/images/Shirt/liverpool/ao7.jpg"),
    liverpool8: require("~/assests/images/Shirt/liverpool/ao8.jpg"),
    liverpool9: require("~/assests/images/Shirt/liverpool/ao9.jpg"),
    liverpool10: require("~/assests/images/Shirt/liverpool/ao10.jpg"),
    liverpool11: require("~/assests/images/Shirt/liverpool/ao11.jpg"),
    liverpool12: require("~/assests/images/Shirt/liverpool/ao12.jpg"),

    manutd1: require("~/assests/images/Shirt/manutd/ao1.jpg"),
    manutd2: require("~/assests/images/Shirt/manutd/ao2.jpg"),
    manutd3: require("~/assests/images/Shirt/manutd/ao3.jpg"),
    manutd4: require("~/assests/images/Shirt/manutd/ao4.jpg"),
    manutd5: require("~/assests/images/Shirt/manutd/ao5.jpg"),
    manutd6: require("~/assests/images/Shirt/manutd/ao6.jpg"),
    manutd7: require("~/assests/images/Shirt/manutd/ao7.jpg"),
    manutd8: require("~/assests/images/Shirt/manutd/ao8.jpg"),
    manutd9: require("~/assests/images/Shirt/manutd/ao9.jpg"),
    manutd10: require("~/assests/images/Shirt/manutd/ao10.jpg"),
    manutd11: require("~/assests/images/Shirt/manutd/ao11.jpg"),
    manutd12: require("~/assests/images/Shirt/manutd/ao12.jpg"),

    atletico1: require("~/assests/images/Shirt/atletico/ao1.png"),
    atletico2: require("~/assests/images/Shirt/atletico/ao2.jpg"),

    barcelona1: require("~/assests/images/Shirt/barcelona/ao1.jpg"),
    barcelona2: require("~/assests/images/Shirt/barcelona/ao2.jpg"),
    barcelona3: require("~/assests/images/Shirt/barcelona/ao3.jpg"),
    barcelona4: require("~/assests/images/Shirt/barcelona/ao4.jpg"),
    barcelona5: require("~/assests/images/Shirt/barcelona/ao5.jpg"),
    barcelona6: require("~/assests/images/Shirt/barcelona/ao6.jpg"),
    barcelona7: require("~/assests/images/Shirt/barcelona/ao7.jpg"),
    barcelona8: require("~/assests/images/Shirt/barcelona/ao8.jpg"),

    realmadrid1: require("~/assests/images/Shirt/realmadrid/ao1.jpg"),
    realmadrid2: require("~/assests/images/Shirt/realmadrid/ao2.jpg"),
    realmadrid3: require("~/assests/images/Shirt/realmadrid/ao3.jpg"),
    realmadrid4: require("~/assests/images/Shirt/realmadrid/ao4.jpg"),
    realmadrid5: require("~/assests/images/Shirt/realmadrid/ao5.jpg"),
    realmadrid6: require("~/assests/images/Shirt/realmadrid/ao6.jpg"),
    realmadrid7: require("~/assests/images/Shirt/realmadrid/ao7.jpg"),
    realmadrid8: require("~/assests/images/Shirt/realmadrid/ao8.jpg"),
    realmadrid9: require("~/assests/images/Shirt/realmadrid/ao9.jpg"),
    realmadrid10: require("~/assests/images/Shirt/realmadrid/ao10.jpg"),
    realmadrid11: require("~/assests/images/Shirt/realmadrid/ao11.jpg"),
    realmadrid12: require("~/assests/images/Shirt/realmadrid/ao12.jpg"),

    bayern1: require("~/assests/images/Shirt/bayern/ao1.jpg"),
    bayern2: require("~/assests/images/Shirt/bayern/ao2.jpg"),
    bayern3: require("~/assests/images/Shirt/bayern/ao3.jpg"),
    bayern4: require("~/assests/images/Shirt/bayern/ao4.jpg"),
    bayern5: require("~/assests/images/Shirt/bayern/ao5.jpg"),
    bayern6: require("~/assests/images/Shirt/bayern/ao6.jpg"),
    bayern7: require("~/assests/images/Shirt/bayern/ao7.jpg"),
    bayern8: require("~/assests/images/Shirt/bayern/ao8.jpg"),
    bayern9: require("~/assests/images/Shirt/bayern/ao9.jpg"),
    bayern10: require("~/assests/images/Shirt/bayern/ao10.jpg"),
    bayern11: require("~/assests/images/Shirt/bayern/ao11.jpg"),
    bayern12: require("~/assests/images/Shirt/bayern/ao12.jpg"),

    dortmund1: require("~/assests/images/Shirt/dortmund/ao1.jpg"),
    dortmund2: require("~/assests/images/Shirt/dortmund/ao2.jpg"),
    dortmund3: require("~/assests/images/Shirt/dortmund/ao3.jpg"),
    dortmund4: require("~/assests/images/Shirt/dortmund/ao4.jpg"),
    dortmund5: require("~/assests/images/Shirt/dortmund/ao5.jpg"),
    dortmund6: require("~/assests/images/Shirt/dortmund/ao6.jpg"),
    dortmund7: require("~/assests/images/Shirt/dortmund/ao7.jpg"),
    dortmund8: require("~/assests/images/Shirt/dortmund/ao8.jpg"),

    milan1: require("~/assests/images/Shirt/milan/ao1.jpg"),
    milan2: require("~/assests/images/Shirt/milan/ao2.jpg"),
    milan3: require("~/assests/images/Shirt/milan/ao3.jpg"),
    milan4: require("~/assests/images/Shirt/milan/ao4.jpg"),
    milan5: require("~/assests/images/Shirt/milan/ao5.jpg"),
    milan6: require("~/assests/images/Shirt/milan/ao6.jpg"),
    milan7: require("~/assests/images/Shirt/milan/ao7.jpg"),
    milan8: require("~/assests/images/Shirt/milan/ao8.jpg"),
    milan9: require("~/assests/images/Shirt/milan/ao9.jpg"),
    milan10: require("~/assests/images/Shirt/milan/ao10.jpg"),

    roma1: require("~/assests/images/Shirt/roma/ao1.jpg"),
    roma2: require("~/assests/images/Shirt/roma/ao2.jpg"),
    roma3: require("~/assests/images/Shirt/roma/ao3.jpg"),
    roma4: require("~/assests/images/Shirt/roma/ao4.jpg"),

    intermilan1: require("~/assests/images/Shirt/intermilan/ao1.jpg"),
    intermilan2: require("~/assests/images/Shirt/intermilan/ao2.jpg"),
    intermilan3: require("~/assests/images/Shirt/intermilan/ao3.jpg"),
    intermilan4: require("~/assests/images/Shirt/intermilan/ao4.jpg"),
    intermilan5: require("~/assests/images/Shirt/intermilan/ao5.jpg"),
    intermilan6: require("~/assests/images/Shirt/intermilan/ao6.jpg"),

    juventus1: require("~/assests/images/Shirt/juventus/ao1.jpg"),
    juventus2: require("~/assests/images/Shirt/juventus/ao2.jpg"),
    juventus3: require("~/assests/images/Shirt/juventus/ao3.jpg"),
    juventus4: require("~/assests/images/Shirt/juventus/ao4.jpg"),
    juventus5: require("~/assests/images/Shirt/juventus/ao5.jpg"),
    juventus6: require("~/assests/images/Shirt/juventus/ao6.jpg"),

    psg1: require("~/assests/images/Shirt/psg/ao1.jpg"),
    psg2: require("~/assests/images/Shirt/psg/ao2.jpg"),
    psg3: require("~/assests/images/Shirt/psg/ao3.jpg"),
    psg4: require("~/assests/images/Shirt/psg/ao4.jpg"),
    psg5: require("~/assests/images/Shirt/psg/ao5.jpg"),
    psg6: require("~/assests/images/Shirt/psg/ao6.jpg"),
};

export default images;
