const images = {
    logo: require("~/assests/images//hiequego.png"),
    arsenal: require("~/assests/images/logos/arsenal.png"),
    chelsea: require("~/assests/images/logos/chelsea.png"),
    liverpool: require("~/assests/images/logos/liverpool.png"),
    mancity: require("~/assests/images/logos/manchestercity.png"),
    manutd: require("~/assests/images/logos/manchesterunited.png"),
    tottenham: require("~/assests/images/logos/tottenham.png"),
    atletico: require("~/assests/images/logos/atleticomadrid.png"),
    barcelona: require("~/assests/images/logos/barcelona.png"),
    realmadrid: require("~/assests/images/logos/realmadrid.png"),
    bayern: require("~/assests/images/logos/bayernmunich.png"),
    dortmund: require("~/assests/images/logos/dortmund.png"),
    acmilan: require("~/assests/images/logos/acmilan.png"),
    roma: require("~/assests/images/logos/asroma.png"),
    intermilan: require("~/assests/images/logos/intermilan.png"),
    juventus: require("~/assests/images/logos/juventus.png"),
    psg: require("~/assests/images/logos/psg.png"),
    mls: require("~/assests/images/logos/MLS.png"),
    spl: require("~/assests/images/logos/SPL.png"),

    mancity1: require("~/assests/images/Shirt/mancity/ao1.jpg"),
    mancity2: require("~/assests/images/Shirt/mancity/ao2.jpg"),
    mancity3: require("~/assests/images/Shirt/mancity/ao3.jpg"),
    mancity4: require("~/assests/images/Shirt/mancity/ao4.jpg"),
    mancity5: require("~/assests/images/Shirt/mancity/ao5.jpg"),
    mancity6: require("~/assests/images/Shirt/mancity/ao6.jpg"),
    mancity7: require("~/assests/images/Shirt/mancity/ao7.jpg"),
    mancity8: require("~/assests/images/Shirt/mancity/ao8.jpg"),
    mancity9: require("~/assests/images/Shirt/mancity/ao9.jpg"),
    mancity10: require("~/assests/images/Shirt/mancity/ao10.jpg"),
    mancity11: require("~/assests/images/Shirt/mancity/ao11.jpg"),
    mancity12: require("~/assests/images/Shirt/mancity/ao12.jpg"),
};

export default images;
